In [1]:
from pyspark.sql import SparkSession
spark =SparkSession.builder.appName("Basic").getOrCreate()

In [2]:
from pyspark.ml.feature import OneHotEncoderEstimator

df = spark.createDataFrame([
    (0.0, 1.0),
    (1.0, 0.0),
    (2.0, 1.0),
    (0.0, 2.0),
    (0.0, 1.0),
    (3.0, 1.0),
    (4.0, 1.0),
    (5.0, 1.0),
    (6.0, 1.0),
    (7.0, 1.0),
    (8.0, 1.0)
    
], ["categoryIndex1", "categoryIndex2"])

encoder = OneHotEncoderEstimator(
            inputCols=["categoryIndex1", "categoryIndex2"],
            outputCols=["categoryVec1", "categoryVec2"])
model = encoder.fit(df)
encoded = model.transform(df)
encoded.toPandas()

,categoryIndex1,categoryIndex2,categoryVec1,categoryVec2
0,0.0,1.0,"(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"
1,1.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(1.0, 0.0)"
2,2.0,1.0,"(0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"
3,0.0,2.0,"(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 0.0)"
4,0.0,1.0,"(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"
5,3.0,1.0,"(0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"
6,4.0,1.0,"(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"
7,5.0,1.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)","(0.0, 1.0)"
8,6.0,1.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)","(0.0, 1.0)"
9,7.0,1.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)","(0.0, 1.0)"
10,8.0,1.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)","(0.0, 1.0)"

In [3]:
from pyspark.ml.feature import Imputer

df = spark.createDataFrame([
    (1.0, float("nan")),
    (2.0, float("nan")),
    (float("nan"), 3.0),
    (4.0, 4.0),
    (5.0, 5.0),
    (5.0, 5.0)
], ["a", "b"])

imputer = Imputer(inputCols=["a", "b"], outputCols=["out_a", "out_b"],strategy="mean")
model = imputer.fit(df)

model.transform(df).show()

+---+---+-----+-----+
|  a|  b|out_a|out_b|
+---+---+-----+-----+
|1.0|NaN|  1.0| 4.25|
|2.0|NaN|  2.0| 4.25|
|NaN|3.0|  3.4|  3.0|
|4.0|4.0|  4.0|  4.0|
|5.0|5.0|  5.0|  5.0|
|5.0|5.0|  5.0|  5.0|
+---+---+-----+-----+